# Generated by Django 4.2.3 on 2023-09-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping_cart", "0003_remove_shopping_cart_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopping_cart",
            name="product",
            field=models.CharField(max_length=40),
        ),
    ]
