# Generated by Django 4.2.3 on 2023-07-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_details',
            field=models.CharField(max_length=32),
        ),
    ]
