# Generated by Django 4.2.3 on 2023-09-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_order_shopping_cart_remove_order_delivery_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="items",
            field=models.CharField(max_length=20),
        ),
    ]
